test_name: Full CRUD Flow

stages:
  - name: Create a new object
    request:
      url: "{tavern.env_vars.BASE_URL}/objects"
      method: POST
      json:
        name: "Apple MacBook Pro 16"
        data:
          year: 2025
          price: 1849.99
          CPU model: "Intel Core i9"
          Hard disk size: "1 TB"
    response:
      status_code: 200
      json:
        id: !anystr
        name: "{tavern.request_vars.json.name}"
        createdAt: !anystr
        data: 
          year: !int "{tavern.request_vars.json.data.year}"
          price: !float "{tavern.request_vars.json.data.price}"
          CPU model: "{tavern.request_vars.json.data.CPU model}"
          Hard disk size: "{tavern.request_vars.json.data.Hard disk size}"

      save:
        json:
          created_object_id: id

  - name: Retrieve the created post
    request:
      url: "{tavern.env_vars.BASE_URL}/objects/{created_object_id}"
      method: GET
    response:
      status_code: 200
      json:
        id: "{created_object_id}"
        name: "Apple MacBook Pro 16"
        data:
          year: 2025
          price: 1849.99
          CPU model: "Intel Core i9"
          Hard disk size: "1 TB"
  
  - name: Update the created object
    request:
      url: "{tavern.env_vars.BASE_URL}/objects/{created_object_id}"
      method: PUT
      json:
        name: "Apple MacBook Pro 16"
        data:
          year: 2025
          price: 1849.99
          CPU model: "Intel Core i9"
          Hard disk size: "1 TB"
          color: "silver"
    response:
      status_code: 200
      json:
        id: "{created_object_id}"
        name: "{tavern.request_vars.json.name}"
        data:
          year: !int "{tavern.request_vars.json.data.year}"
          price: !float "{tavern.request_vars.json.data.price}"
          CPU model: "{tavern.request_vars.json.data.CPU model}"
          Hard disk size: "{tavern.request_vars.json.data.Hard disk size}"
          color: "{tavern.request_vars.json.data.color}"
        updatedAt: !anystr
